# Generated by Django 3.1.5 on 2021-01-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('ra', models.CharField(max_length=15)),
                ('dec', models.CharField(max_length=15)),
            ],
        ),
    ]
